Task2
kystttt/botaholka pull request #18
Opened 2024-10-21 18:12 UTC by Ibaaan

2024-10-27 19:22 UTC, vpyzhyanov requested changes
есть куда расти. 

В следующий раз сырой код даже смотреть не буду! Учитесь работать в команде и использовать пулл реквесты, так будет намного проще.

2024-10-27 19:22 UTC, vpyzhyanov commented on src/main/java/TextHandler.java
> +        for (Integer key : listOfOrders.getHashMap().keySet()) {
аналогично очень не эффективно

2024-10-27 19:22 UTC, vpyzhyanov commented on src/main/java/TextHandler.java
> +    //TODO Измени с учётом нового класса Menu
ай яй яй

2024-10-27 19:22 UTC, vpyzhyanov commented on src/main/java/TextHandler.java
> +            Iterator<String> keys = jsonObject.keySet().iterator();
похоже вы не ищете лёгких путей. Простой foreach (который for) был бы лучшим выбором

2024-10-27 19:22 UTC, vpyzhyanov commented on src/main/java/TextHandler.java
> +            throw new RuntimeException(e);
человекочитаемое сообщеение

2024-10-27 19:22 UTC, vpyzhyanov commented on src/main/java/TextHandler.java
> +            output_message = "У вас нету действительных заказов";
надо учить русский язык

2024-10-27 19:22 UTC, vpyzhyanov commented on src/test/java/CommandAddToCARTCommandCartAndCommandDeleteTest.java
> +public class CommandAddToCARTCommandCartAndCommandDeleteTest {
так классы никто и никогда не называет. Пишите что конкретно вы тестируете, какой класс тестируете. Например `TextHandlerTest`

2024-10-27 19:22 UTC, vpyzhyanov commented on src/test/java/CommandAddToCARTCommandCartAndCommandDeleteTest.java
> +        testMenuList.setPrevCommand("/menu");
В идеале этот метод в тесте вообще не должен быть доступен

2024-10-27 19:22 UTC, vpyzhyanov commented on src/test/java/CommandAddToCARTCommandCartAndCommandDeleteTest.java
> +        assertTrue(testMenuList.getCart().contains("1. Шаурма - 250 рублей"));
смысл в этой проверке отстутстсвует, т.к. вы сами туда это значение положили, следовательно она пройдёт абсолютно всегда

2024-10-27 19:22 UTC, vpyzhyanov commented on src/test/java/CommandAddToCARTCommandCartAndCommandDeleteTest.java
> +        testMenuList.setPrevCommand("/delete");
вы тестируете насколько хорошо у вас получается хачить внутреннюю логику, а не саму логику.

2024-10-27 19:22 UTC, vpyzhyanov commented on src/test/java/CommandAddToCARTCommandCartAndCommandDeleteTest.java
> +        textHandler.viewCart();
метод не должен быть публичным. Тем более он ничего не возвращает, значит смысла в нём ноль.

2024-10-27 19:22 UTC, vpyzhyanov commented on src/test/java/CommandAddToCARTCommandCartAndCommandDeleteTest.java
> +        textHandler.deleteFromCart("0");
инкапсуляция отсутствует. метод не должен быть публичным. Тем более он ничего не возвращает, значит смысла в нём ноль.

2024-10-27 19:22 UTC, vpyzhyanov commented on src/test/java/ListOfOrdersTest.java
> +    void testGetValue1() {
тест ничем не отличается от предыдущего

2024-10-27 19:22 UTC, vpyzhyanov commented on src/test/java/ListOfOrdersTest.java
> +    void testGetValue2() {
некорректное имя теста

2024-10-27 19:22 UTC, vpyzhyanov commented on src/test/java/ListOfOrdersTest.java
> +        Assertions.assertEquals(order, listOfOrders.getValue(1));
такой тест уже есть

2024-10-27 19:22 UTC, vpyzhyanov commented on src/test/java/TestCommandMenu.java
> +        try (FileWriter file = new FileWriter("src/main/resources/menu.json")) {
1. должны использовать ресурсы из тестов, а не из основного кода
2. Вы допустили критическую ошибку и перезаписываете системный файл ресурсов. Это очень плохо!

2024-10-27 19:22 UTC, vpyzhyanov commented on src/test/java/TestCommandMenu.java
> +    private ListOfOrders testListOfOrders;
не используется

2024-10-27 19:22 UTC, vpyzhyanov commented on src/test/java/TestCommandMenu.java
> +    public void testMenuCalling() {
явно этот тест не тестирует то, что вы хотели. Да и он ломает всё приложение целиком.

2024-10-27 19:22 UTC, vpyzhyanov commented on src/test/java/TextHandlerTest.java
> + *       <li>commandCancelOrder</li>
а остальные?

2024-10-27 19:22 UTC, vpyzhyanov commented on src/test/java/TextHandlerTest.java
> +     * Обнуляет ListOfOrders и добавляет в menu.json несколько пунктов из меню
это неправда

2024-10-27 19:22 UTC, vpyzhyanov commented on src/test/java/TextHandlerTest.java
> +        Assertions.assertEquals(2, listOfOrders.getHashMap().size());
тест не полный. Он не проверил какой именно заказ продублирван и чем он наполнен

2024-10-31 12:33 UTC, Ibaaan commented on src/main/java/ListOfOrders.java
> +    public void clearList(){
Исправлено

2024-10-31 12:34 UTC, Ibaaan commented on src/main/java/MenuList.java
> +    private ArrayList<String> cart;
Мы полностью переделали этот класс, на два других: Cart и Menu

2024-10-31 12:46 UTC, Ibaaan commented on src/main/java/MenuLogic/HashMapMenu.java
> +    public HashMap<S, I> getHashMap(){
Исправлено в c44dc9fd

2024-10-31 12:46 UTC, Ibaaan commented on src/main/java/MenuLogic/Menu.java
> +package MenuLogic;
Исправлено

2024-10-31 12:47 UTC, Ibaaan commented on src/main/java/MenuLogic/Menu.java
> +public class Menu extends HashMapMenu<String, Integer>{
Исправлено

2024-10-31 12:48 UTC, Ibaaan commented on src/main/java/MenuLogic/HashMapMenu.java
> +public abstract class HashMapMenu<S, I> {
Исправлено

2024-10-31 12:49 UTC, Ibaaan commented on src/main/java/MenuLogic/HashMapMenu.java
> +public abstract class HashMapMenu<S, I> {
Исправлено

2024-10-31 12:49 UTC, Ibaaan commented on src/main/java/MenuLogic/HashMapMenu.java
> +    HashMap<S, I> menuList;
Исправлено

2024-10-31 12:49 UTC, Ibaaan commented on src/main/java/MenuLogic/Menu.java
> +     * Возвращает цену блюда в меню по ее названию
Исправлено

2024-10-31 12:49 UTC, Ibaaan commented on src/main/java/MenuLogic/Menu.java
> +            throw new NullPointerException("Такого блюда в меню нету");
Исправлено

2024-10-31 12:51 UTC, Ibaaan commented on src/main/java/MenuLogic/Menu.java
> +            throw new NullPointerException("Такого блюда в меню нету");
Строчка переделана

2024-10-31 12:52 UTC, Ibaaan commented on src/main/java/Order.java
> +//    private enum StatusState{
Удалено

2024-10-31 12:52 UTC, Ibaaan commented on src/main/java/Order.java
> +    private int order_id;
Исправлено

2024-10-31 12:53 UTC, Ibaaan commented on src/main/java/Order.java
> +//    private StatusState statusState;
Удалено

2024-10-31 12:53 UTC, Ibaaan commented on src/main/java/Order.java
> +//    private final String timeTo = "К ближайшему";
Удалено

2024-10-31 12:58 UTC, Ibaaan commented on src/main/java/Order.java
> +    public int getOrderId(){
Исправлено

2024-10-31 13:01 UTC, Ibaaan commented on src/main/java/Order.java
> +     *Список того что заказа клиент
Исправлено

2024-10-31 13:02 UTC, Ibaaan commented on src/main/java/Order.java
> +    private ArrayList<String> orderList = new ArrayList<>();
Исправлено

2024-10-31 13:07 UTC, Ibaaan commented on src/main/java/TGBot.java
> +    import java.awt.*;
Этого уже нет, и зачем оно было тоже не знаю

2024-10-31 13:07 UTC, Ibaaan commented on src/main/java/TGBot.java
> +        private ListOfOrders listOfOrders;
Исправлено

2024-10-31 13:14 UTC, Ibaaan commented on src/main/java/TGBot.java
> +        private MenuList menuList;
Исправлено

2024-10-31 13:15 UTC, Ibaaan commented on src/main/java/TextHandler.java
> +    public TextHandler(ListOfOrders listOfOrders, MenuList menuList) {
Исправлено

2024-10-31 13:30 UTC, Ibaaan commented on src/main/java/TextHandler.java
> +    public String getOutputMassage(String message_text, Long chat_id) {
Удалён геттер getOutputMassage, теперь его функции выполняет метод logic переименованный в proccessMessage

2024-10-31 13:31 UTC, Ibaaan commented on src/main/java/TextHandler.java
> +    private void logic(String message_text, Long chat_id) {
logic переименованный в proccessMessage

2024-10-31 13:38 UTC, Ibaaan commented on src/main/java/TextHandler.java
> +    //TODO Измени с учётом нового класса Menu
Не успели доделать до вашего код ревью

2024-10-31 13:39 UTC, Ibaaan commented on src/main/java/TextHandler.java
> +    //TODO Измени с учётом нового класса Menu
Удалено

2024-10-31 13:41 UTC, Ibaaan commented on src/main/java/TextHandler.java
> +            throw new RuntimeException(e);
Исправлено

2024-10-31 13:43 UTC, Ibaaan commented on src/main/java/TextHandler.java
> +            output_message = "У вас нету действительных заказов";
Исправлено

2024-10-31 13:51 UTC, Ibaaan commented on src/test/java/TestCommandMenu.java
> +        try (FileWriter file = new FileWriter("src/main/resources/menu.json")) {
Исправлено

2024-10-31 13:55 UTC, Ibaaan commented on src/main/java/Main.java
>              e.printStackTrace();
Исправлено

2024-10-31 13:55 UTC, Ibaaan commented on src/main/java/MenuList.java
> +    private String prevcommand;
Исправлено

2024-10-31 13:56 UTC, Ibaaan commented on src/main/java/MenuList.java
> +    public String getMenuListValue(int index) {
Переделан MenuList

2024-10-31 13:56 UTC, Ibaaan commented on src/main/java/MenuList.java
> +    public HashMap<Integer, String> getMenulist() {
Переделан MenuList

2024-10-31 13:57 UTC, Ibaaan commented on src/main/java/MenuList.java
> +     В случае, если индекса не существует возвращает константу ERROR_INDEX_CONST = ""Такого индекса не существует\n";"
Класс MenuList переделан на два класса: Menu и Cart

2024-10-31 13:57 UTC, Ibaaan commented on src/main/java/MenuList.java
> + чтобы меню можно было удобно использовать в разных участках кода.
Переделан MenuList

2024-10-31 13:58 UTC, Ibaaan commented on src/main/java/MenuList.java
> +    public ArrayList<String> getCart() {
Переделан MenuList

2024-10-31 13:58 UTC, Ibaaan commented on src/main/java/MenuList.java
> +        return prevcommand;
Переделан MenuList

2024-10-31 13:59 UTC, Ibaaan commented on src/main/java/Order.java
> + * Класс заказа
Хорошо

2024-10-31 14:00 UTC, Ibaaan commented on src/main/java/TGBot.java
> +        private ListOfOrders listOfOrders;
Исправлено

2024-10-31 14:00 UTC, Ibaaan commented on src/main/java/TGBot.java
> +        private MenuList menuList;
Исправлено

2024-10-31 14:00 UTC, Ibaaan commented on src/main/java/TGBot.java
> +        private final Menu menu;
Исправлено

2024-10-31 14:00 UTC, Ibaaan commented on src/main/java/TGBot.java
> +                TextHandler textHandler = new TextHandler(listOfOrders, menuList, menu);
Исправлено

2024-10-31 14:01 UTC, Ibaaan commented on src/main/java/TextHandler.java
> +        output_message = Constants.START_CONST;
Удалён

2024-10-31 14:01 UTC, Ibaaan commented on src/main/java/TextHandler.java
> +    private void commandHelp() {
Удалён

2024-10-31 14:01 UTC, Ibaaan commented on src/main/java/TextHandler.java
> +    private void commandWrongTypoWord() {
Удален

2024-10-31 14:02 UTC, Ibaaan commented on src/main/java/TextHandler.java
> +        ArrayList<String> cartItems = menuList.getCart();
Да, прочувствовали

2024-10-31 14:02 UTC, Ibaaan commented on src/main/java/TextHandler.java
> +            Iterator<String> keys = jsonObject.keySet().iterator();
Удалён и изменён

2024-10-31 14:03 UTC, Ibaaan commented on src/test/java/CommandAddToCARTCommandCartAndCommandDeleteTest.java
> +        testMenuList.setPrevCommand("/menu");
Исправлен

2024-10-31 14:04 UTC, Ibaaan commented on src/test/java/TextHandlerTest.java
> + *       <li>commandCancelOrder</li>
Изменён JavaDoc

2024-10-31 14:04 UTC, Ibaaan commented on src/test/java/TestCommandMenu.java
> +    public void testMenuCalling() {
Удалён и переписан

2024-10-31 17:42 UTC, Ibaaan commented on src/main/java/Order.java
> +    public String formMessageForClient(Menu menu) {
Исправил

2024-10-31 17:46 UTC, Ibaaan commented on src/main/java/TextHandler.java
> +                menuList.setPrevCommand(message_text);
Изменено, вызывается только один раз

2024-10-31 17:46 UTC, Ibaaan commented on src/main/java/TextHandler.java
> +        for (Integer key : listOfOrders.getHashMap().keySet()) {
Исправил

2024-10-31 17:46 UTC, Ibaaan commented on src/main/java/TextHandler.java
> +        for (Integer key : listOfOrders.getHashMap().keySet()) {
Исправил

2024-10-31 17:47 UTC, Ibaaan commented on src/test/java/ListOfOrdersTest.java
> +    void testGetValue1() {
Полностью переделал класс OrderList

2024-10-31 17:48 UTC, Ibaaan commented on src/test/java/ListOfOrdersTest.java
> +    void testGetValue2() {
Полностью переделал класс OrderList -> тест больше не нужен

2024-10-31 17:49 UTC, Ibaaan commented on src/test/java/TestCommandMenu.java
> +        try (FileWriter file = new FileWriter("src/main/resources/menu.json")) {
Изменена работа с меню -> тест изменён

2024-10-31 17:49 UTC, Ibaaan commented on src/test/java/TestCommandMenu.java
> +    private ListOfOrders testListOfOrders;
Аналогично, тест больше не нужен

2024-10-31 17:50 UTC, Ibaaan commented on src/test/java/TextHandlerTest.java
> +     * Обнуляет ListOfOrders и добавляет в menu.json несколько пунктов из меню
Исправлено

2024-10-31 18:09 UTC, Ibaaan commented on src/main/java/TextHandler.java
> +                break;
исправлено

2024-10-31 18:09 UTC, Ibaaan commented on src/main/java/TextHandler.java
> +    private String output_message = "";
Исправлено

2024-10-31 18:24 UTC, Ibaaan commented on src/main/java/TextHandler.java
> +    //TODO Это конструктор чтобы ничего не поломалось,
Не успели доделать все поправки в коде, до вашего код ревью

2024-10-31 18:32 UTC, Ibaaan commented on src/main/java/Main.java
> +        Menu menu = new Menu(Constants.MENU_FILENAME_CONST);
Исправлено

2024-10-31 18:32 UTC, Ibaaan commented on src/main/java/TGBot.java
>                      e.printStackTrace();
Исправлено

2024-10-31 19:24 UTC, Ibaaan commented on src/test/java/CommandAddToCARTCommandCartAndCommandDeleteTest.java
> +        textHandler.viewCart();
Метод не публичный

2024-10-31 19:25 UTC, Ibaaan commented on src/test/java/CommandAddToCARTCommandCartAndCommandDeleteTest.java
> +        textHandler.deleteFromCart("0");
Исправлено

2024-10-31 19:39 UTC, Ibaaan commented on src/test/java/CommandAddToCARTCommandCartAndCommandDeleteTest.java
> +        assertTrue(testMenuList.getCart().contains("1. Шаурма - 250 рублей"));
Исправлено

2024-11-04 18:29 UTC, vpyzhyanov commented on src/main/java/TextHandler.java
> +    //TODO Это конструктор чтобы ничего не поломалось,
Я к тому, что все ваши изменения должны быть в ваших именных ветках. А в ветке task2 должно быть уже итоговое решение, в котором вы правите только замечания

2024-11-04 18:32 UTC, vpyzhyanov commented on src/main/java/ListOfOrders.java
> +    private HashMap<Integer, Order> orders;
ой ой ой, что вы наделали?! Вместо того, чтобы использовать интерфейсы в сделали совершенного нелогичное искусственное наследование

![image](https://github.com/user-attachments/assets/a76bd3ea-9571-424c-96b3-a7bf609ecdc9)

Уберите это, верните поле обратно и **используйте интерфейсы**

2024-11-04 18:34 UTC, vpyzhyanov commented on src/main/java/ListOfOrders.java
> +    public void clearList(){
по факту ничего не исправлено. Метод как был публичным так и остался. Зато появилось ещё куча публичных методов, которые к этому классу имеют слабое отношение и точно так же снижают инкапсуляцию в ноль

2024-11-04 18:38 UTC, vpyzhyanov commented on src/main/java/Main.java
> +        Menu menu = new Menu(Constants.MENU_FILENAME_CONST);
Я надеялся, что вы исправите не бездумно, а подумаете и пронесёте замечание дальше. То есть сейчас я могу написать ровно такое же замечание, только с другими именами:

эти объекты используются только в одном **TextHandler**, поэтому и должны создавать там, а не здесь. Здесь они не нужны.

2024-11-04 18:42 UTC, vpyzhyanov commented on src/main/java/MenuList.java
> +    private ArrayList<String> cart;
Это не освобождает вас от исправления замечания!!! Ничего не исправлено!!!

![image](https://github.com/user-attachments/assets/7ab20095-16db-4101-8f13-b4d44d57c66b)

2024-11-04 18:47 UTC, vpyzhyanov commented on src/main/java/MenuList.java
> +     В случае, если индекса не существует возвращает константу ERROR_INDEX_CONST = ""Такого индекса не существует\n";"
Это не освобождает вас от исправления замечания!!!!

![image](https://github.com/user-attachments/assets/44f099aa-1465-40a9-aa4e-9da926d1d9e0)

2024-11-04 18:49 UTC, vpyzhyanov commented on src/main/java/MenuList.java
> + чтобы меню можно было удобно использовать в разных участках кода.
Замечание не исправлено!!! Вы специально так делаете?! Вот только зачем?

![image](https://github.com/user-attachments/assets/f4d94283-710c-42e2-92a3-4cfec4724ac5)

2024-11-04 18:52 UTC, vpyzhyanov commented on src/main/java/MenuList.java
> +    public ArrayList<String> getCart() {
Да вы точно издеваетесь! Дальше проверять не буду!

Срежу вам баллы, может не будете так делать больше. И вы получаете первое предупреждение!

2024-11-06 21:17 UTC, merged